--- #YAML:1.0
name:               Lemonldap-NG-Cli
version:            0.1
abstract:           Command Line Interface to edit LemonLDAP::NG configuration.
author:
    - David Delassus <david.jose.delassus@gmail.com>
license:            unknown
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:
    Lemonldap::NG::Common::Conf:  1
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.57_05
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
